spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:1234/yandex_delivery
    username: postgres
    password: oleg2004
    driverClassName: org.postgresql.Driver
